### ISSUE TITLE
does nothing but download stuff, doesn't matter witch command i use

### ISSUE THREAD

**Issue by infernvs** [mmone/marlintool#1]
➜  marlintool git:(master) ./marlintool.sh -s
./marlintool.sh: 41: ./marlintool.sh: function: not found
-e
Downloading Arduino environment ...

--2017-05-02 14:25:18--  http://downloads-02.arduino.cc/arduino-1.8.2-linuxarm.tar.xz
Resolving downloads-02.arduino.cc (downloads-02.arduino.cc)... 158.69.86.55
Connecting to downloads-02.arduino.cc (downloads-02.arduino.cc)|158.69.86.55|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 78667712 (75M) [application/octet-stream]
Saving to: ‘arduino-1.8.2-linuxarm.tar.xz’

arduino-1.8.2-linuxarm.tar. 100%[===========================================>]  75.02M  14.6MB/s   in 6.1s

2017-05-02 14:25:25 (12.2 MB/s) - ‘arduino-1.8.2-linuxarm.tar.xz’ saved [78667712/78667712]

-e
Unpacking Arduino environment. This might take a while ...
./marlintool.sh: 53: ./marlintool.sh: function: not found
-e
Downloading libraries ...

Cloning into 'LiquidCrystal_I2C'...
remote: Counting objects: 7, done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 7
Unpacking objects: 100% (7/7), done.
Checking connectivity... done.
Cloning into 'LiquidTWI2'...
remote: Counting objects: 126, done.
remote: Total 126 (delta 0), reused 0 (delta 0), pack-reused 126
Receiving objects: 100% (126/126), 29.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (68/68), done.
Checking connectivity... done.
Cloning into 'U8glib_Arduino'...
remote: Counting objects: 270, done.
remote: Total 270 (delta 0), reused 0 (delta 0), pack-reused 270
Receiving objects: 100% (270/270), 1.31 MiB | 1.34 MiB/s, done.
Resolving deltas: 100% (157/157), done.
Checking connectivity... done.
./marlintool.sh: 73: ./marlintool.sh: function: not found
-e
Cloning Marlin "https://github.com/SkyNet3D/Marlin"...

Cloning into 'Marlin'...
remote: Counting objects: 53894, done.
remote: Total 53894 (delta 0), reused 0 (delta 0), pack-reused 53894
Receiving objects: 100% (53894/53894), 39.94 MiB | 10.67 MiB/s, done.
Resolving deltas: 100% (35230/35230), done.
Checking connectivity... done.

➜  marlintool git:(master) ✗ ./marlintool.sh -u
./marlintool.sh: 41: ./marlintool.sh: function: not found
-e
Downloading Arduino environment ...

--2017-05-02 14:26:17--  http://downloads-02.arduino.cc/arduino-1.8.2-linuxarm.tar.xz
Resolving downloads-02.arduino.cc (downloads-02.arduino.cc)... 158.69.86.55
Connecting to downloads-02.arduino.cc (downloads-02.arduino.cc)|158.69.86.55|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 78667712 (75M) [application/octet-stream]
Saving to: ‘arduino-1.8.2-linuxarm.tar.xz’

arduino-1.8.2-linuxarm.tar.xz                               100%[==========================================================================================================================================>]  75.02M  15.7MB/s   in 5.4s

2017-05-02 14:26:23 (13.8 MB/s) - ‘arduino-1.8.2-linuxarm.tar.xz’ saved [78667712/78667712]

mkdir: cannot create directory ‘./arduino’: File exists
-e
Unpacking Arduino environment. This might take a while ...
./marlintool.sh: 53: ./marlintool.sh: function: not found
-e
Downloading libraries ...

Cloning into 'LiquidCrystal_I2C'...
remote: Counting objects: 7, done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 7
Unpacking objects: 100% (7/7), done.
Checking connectivity... done.
Cloning into 'LiquidTWI2'...
remote: Counting objects: 126, done.
remote: Total 126 (delta 0), reused 0 (delta 0), pack-reused 126
Receiving objects: 100% (126/126), 29.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (68/68), done.
Checking connectivity... done.
Cloning into 'U8glib_Arduino'...
remote: Counting objects: 270, done.
remote: Total 270 (delta 0), reused 0 (delta 0), pack-reused 270
Receiving objects: 100% (270/270), 1.31 MiB | 2.24 MiB/s, done.
Resolving deltas: 100% (157/157), done.
Checking connectivity... done.
./marlintool.sh: 73: ./marlintool.sh: function: not found
-e
Cloning Marlin "https://github.com/SkyNet3D/Marlin"...

fatal: destination path 'Marlin' already exists and is not an empty directory.

**Comment by mmone** [comment]
Hi infernvs, On which OS are you running the build?

**Comment by infernvs** [comment]
I've tried on Debian and Armbian wich is where my 3d printer is connected.  Meanwhile, i found out that the script doesn't have on top wich shell to use, so put #! /bin/bash on the script and it work, like a charm!

**Comment by mmone** [comment]
Thanks for the fix. I pushed the changes.
