### ISSUE TITLE
Setup fails after upgrade

### ISSUE THREAD

**Issue by uuzi** [mmone/marlintool#11]
asince updating marlintool I can't get it to fetch the marlin sources or the dependancies

`./marlintool.sh -s

Setting up build environment in "./arduino" ...

Downloading Arduino environment ...

--2018-03-19 17:01:59--  http://downloads-02.arduino.cc/arduino--linuxarm.tar.xz
Resolving downloads-02.arduino.cc (downloads-02.arduino.cc)... 158.69.86.55
Connecting to downloads-02.arduino.cc (downloads-02.arduino.cc)|158.69.86.55|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-19 17:01:59 ERROR 404: Not Found.

Unpacking Arduino environment. This might take a while ...

tar: arduino--linuxarm.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
rm: cannot remove 'arduino--linuxarm.tar.xz': No such file or directory

Downloading libraries ...

Cloning into 'LiquidCrystal_I2C'...
remote: Counting objects: 7, done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 7
Unpacking objects: 100% (7/7), done.
mv: cannot move 'LiquidCrystal_I2C/LiquidCrystal_I2C' to '/libraries/LiquidCrystal_I2C': No such file or directory
Cloning into 'LiquidTWI2'...
remote: Counting objects: 126, done.
remote: Total 126 (delta 0), reused 0 (delta 0), pack-reused 126
Receiving objects: 100% (126/126), 29.04 KiB | 0 bytes/s, done.
Resolving deltas: 100% (68/68), done.
mv: cannot move 'LiquidTWI2/' to '/libraries/LiquidTWI2': No such file or directory
Cloning into 'U8glib_Arduino'...
remote: Counting objects: 270, done.
remote: Total 270 (delta 0), reused 0 (delta 0), pack-reused 270
Receiving objects: 100% (270/270), 1.31 MiB | 1.10 MiB/s, done.
Resolving deltas: 100% (157/157), done.
mv: cannot move 'U8glib_Arduino/' to '/libraries/U8glib_Arduino': No such file or directory
Cloning into 'TMC2130Stepper'...
remote: Counting objects: 710, done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 710 (delta 22), reused 34 (delta 18), pack-reused 663
Receiving objects: 100% (710/710), 237.98 KiB | 0 bytes/s, done.
Resolving deltas: 100% (429/429), done.
mv: cannot move 'TMC2130Stepper/' to '/libraries/TMC2130Stepper': No such file or directory
`

**Comment by uuzi** [comment]
ahhh i see it doesnt seem to parse the $arduinoToolchainVersion correctly or at all
i'll investigate further

Update: as far as i can judge no variables get parsed from the params file.

**Comment by mmone** [comment]
Should be fixed now.

**Comment by uuzi** [comment]
all working now
